apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - json-text

components:
  - components

# we don't need invalid fields in our manifest :)
patches:
- patch: |-
    - op: remove
      path: /metadata/annotations/template
  target:
    kind: Whatever
    name: whatever
